const sampleData = [
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 5,
    characteristics_id: 158622,
    characteristics_name: 'Fit',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 3,
    characteristics_id: 158623,
    characteristics_name: 'Length',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 4,
    characteristics_id: 158624,
    characteristics_name: 'Comfort',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 1,
    characteristics_id: 158625,
    characteristics_name: 'Quality',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: Date.now(),
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 1,
    characteristics_id: 158622,
    characteristics_name: 'Fit',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: '2021-02-21T05:35:41.000Z',
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 4,
    characteristics_id: 158623,
    characteristics_name: 'Length',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: Date.now(),
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 5,
    characteristics_id: 158624,
    characteristics_name: 'Comfort',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: Date.now(),
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 5,
    characteristics_id: 158625,
    characteristics_name: 'Quality',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
];

const evergreenData = {
  product: '-----',
  productName: '-----',
  meta: {
    product_id: '-----',
    ratings: { 5: '1' },
    recommended: { true: 3, false: 0 },
    characteristics: {
      Fit: { id: 158622, value: '0' },
      Length: { id: 158623, value: '0' },
      Comfort: { id: 158624, value: '0' },
      Quality: { id: 158625, value: '0' },
    },
  },
  results: [
    {
      review_id: 273025,
      rating: 0,
      summary: '-----',
      recommend: false,
      response: null,
      body: '-----',
      date: '2021-01-01T10:21:17.000Z',
      reviewer_name: '-----',
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 273026,
      rating: 0,
      summary: '-----',
      recommend: false,
      response: null,
      body: '-----',
      date: '2021-01-01T14:05:01.000Z',
      reviewer_name: '-----',
      helpfulness: 0,
      photos: [],
    },
  ],
};

module.exports = {
  sampleData,
  evergreenData,
};
