const sampleData = [
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 5,
    characteristics_id: 158622,
    characteristics_name: 'Fit',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 3,
    characteristics_id: 158623,
    characteristics_name: 'Length',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 4,
    characteristics_id: 158624,
    characteristics_name: 'Comfort',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273026,
    rating: 4,
    summary: 'Culpa consequatur nam.',
    recommend: true,
    response: 'null',
    body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
    date: Date.now(),
    reviewer_name: 'Shakira.Marks7',
    helpfulness: 21,
    reported: false,
    characteristics_value: 1,
    characteristics_id: 158625,
    characteristics_name: 'Quality',
    product_name: 'Rhett Jacket',
    photo_url: null,
    photo_id: null,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: Date.now(),
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 1,
    characteristics_id: 158622,
    characteristics_name: 'Fit',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: '2021-02-21T05:35:41.000Z',
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 4,
    characteristics_id: 158623,
    characteristics_name: 'Length',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: Date.now(),
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 5,
    characteristics_id: 158624,
    characteristics_name: 'Comfort',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
  {
    reviews_id: 273027,
    rating: 2,
    summary: 'Voluptatem molestiae consequatur dolores sit.',
    recommend: true,
    response: 'null',
    body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
    date: Date.now(),
    reviewer_name: 'Brando.Dietrich21',
    helpfulness: 13,
    reported: false,
    characteristics_value: 5,
    characteristics_id: 158625,
    characteristics_name: 'Quality',
    product_name: 'Rhett Jacket',
    photo_url: 'https://images.unsplash.com/photo-1536181211993-cf4b2c100475?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80',
    photo_id: 129347,
  },
];

const evergreenData = {
  product: '47421',
  productName: '-----',
  meta: {
    product_id: '47421',
    ratings: { 2: '2', 4: '2' },
    recommended: { true: 3, false: 1 },
    characteristics: {
      Fit: { id: 158622, value: '3.625' },
      Length: { id: 158623, value: '3.125' },
      Comfort: { id: 158624, value: '2' },
      Quality: { id: 158625, value: '2.5' },
    },
  },
  results: [
    {
      review_id: 273025,
      rating: 4,
      summary: 'Nihil sit cupiditate laboriosam nihil ullam quas velit voluptatem.',
      recommend: true,
      response: null,
      body: 'Consectetur quia aut et et sed. In sunt magni aut earum qui aut reprehenderit. Repellendus blanditiis quae incidunt harum. Ut inventore quas.',
      date: '2021-02-08T10:21:17.000Z',
      reviewer_name: 'Presley65',
      helpfulness: 28,
      photos: [],
    },
    {
      review_id: 273026,
      rating: 4,
      summary: 'Culpa consequatur nam.',
      recommend: true,
      response: null,
      body: 'Est aut vel a enim minima. Odio vel rem quam eum facilis iure fugit. Neque corrupti sint. Ex laudantium soluta quisquam odit ut eos atque voluptas. Quia velit odio voluptas saepe qui. Qui placeat molestias praesentium.',
      date: '2021-01-10T14:05:01.000Z',
      reviewer_name: 'Shakira.Marks7',
      helpfulness: 21,
      photos: [],
    },
    {
      review_id: 273027,
      rating: 2,
      summary: 'Voluptatem molestiae consequatur dolores sit.',
      recommend: true,
      response: null,
      body: 'Sint a quia illo iusto quo fugit ullam quos accusantium. Mollitia et fugiat adipisci tempora aliquam debitis sequi possimus. Voluptates laudantium porro atque dolorem. Debitis est quia natus et sunt iure voluptate recusandae.',
      date: '2021-02-21T05:35:41.000Z',
      reviewer_name: 'Brando.Dietrich21',
      helpfulness: 9,
      photos: [],
    },
  ],
};

module.exports = {
  sampleData,
  evergreenData,
};
